# Site
repository: pycqkrdyd.github.io
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: 박용채
title: 자동차 국제 프로세스 ASPICE, ISO21434 기반 Cybersecurity Manager
email: qkrdydpyc@gmail.com
# email_title: Email (Email title override)
website: https://blog.naver.com/qkrdydpyc
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  pycqkrdyd
linkedin_username: qkrdydpyc

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/4310.jpeg
about_content: | # this will include new lines to allow paragraphs
  차량 국제 프로세스, ASPICE, ISO26262 컨설팅 업무를 통해 SW Engineering Process Framework을 기반으로 
  
  양산 내비게이션 SW Cybersecurity Manager로 유럽 판매 예정인 아이오닉6에 탑재되는 내비게이션SW 차량 사이버보안 법규, 
  
  UNECE VTA 인증을 받았습니다. 유럽, 국내, 일본, 북미 등 확대 전개되는 법규 적용을 위해 추가/변경/삭제 되는 사양에 따른 법규 영향성 검토 업무를 수행했습니다.
  
  직접적으로 고객사와 커뮤니케이션하여 보안사양에 대해 협의하고 진행 중인 프로젝트 일정을 지속적으로 확인하여 보안 사양 구현을 위한 일정협의, 
  
  개발 구현 내용 공유, 증빙자료 작성 가이드 등 PM 업무를 지원했습니다.
  
  PM, PO 직무에 관심을 갖고 있습니다.
  
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 내비게이션 SW 사양 관리
        caption: 2022.1 ~ 현재
        description: | 
            [기술스택]
            - JIRA, Confluence, ISO21434, UNECE R.155, UNECE R.156
            
            [진행업무]
            - 추가/변경/삭제된 사양으로 인해 법규 영향(차량 사이버보안 법규, SW 업데이트 법규)이 있는 항목이 있는지 검토
            - 차량 형식 인증을 위한 성적서 작성 및 관리
            - 고객사와 커뮤니케이션하여 개발자 일정 관리
            
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: 내비게이션 SW 개발 프로세스 관리 및 개선
        caption: 2021.5 ~ 2021.12
        description: | 
            [기술스택]
            - JIRA, Confluence, ASPICE, Project Management
            
            [진행업무]
            - CMMI 기반 구축된 자사 개발 프로세스가 잘 적용되고 수행되고 있는지 관리
            - 효율적 업무 수행을 위한 R&R 협의를 통한 사내 개발 프로세스 개선
            - 사업부 대외 운영 업무 수행
            
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: IBM Rhapsody 기반 문서 산출물 IBM Lifecycle Optimization - Publishing 유지보수
        caption: 2020.6 ~ 2021.4
        description: | 
            [기술스택]
            - IBM Rhapsody, UML, IBM Lifecycle Optimization, Javascript, Restful API
            
            [진행업무]
            - ISO26262, ASPICE, Classic AUTOSAR 설계 문서 산출물을 위한 툴 구축
            - 고객사 요구사항에 맞춰 문서 산출물 스크립트 유지보수
            
      - layout: left
        border: weak  # Value of `weak` will display a weak border below this item. # Any 
                      # other value (or no value) means no border will be displayed
        title: ASPICE, ISO26262, Classic AUTOSAR 설계 컨설팅
        caption: 2020.1 ~ 2021.4
        description: | 
            [기술스택]
            - IBM Rhapsody, UML, Classic AUTOSAR
            
            [진행업무]
            - ISO26262, ASPICE, Classic AUTOSAR 설계 컨설팅
            - 차량 SW 설계 구조를 이해하고 UML Dynamic Diagram, Static Diagram 설계 지원
            - 파워트레인, 펌프, 사이드미러 등 다양한 도메인의 차량 SW 프로세스 구축 컨설팅 수행
            
  - title: Experience
    layout: list
    content:
      - layout: right
        title: Hancom MDS
        sub_title: Consultant (직급 사원)
        caption: 2020.01 ~ 2021.04
        link: https://www.hancomit.com/index
        quote: >
          차세대 모빌리티의 핵심 소프트웨어를 쉽게 개발하고 확장 가능한 개발 플랫폼 제공 
        description: | # this will include new lines to allow paragraphs
          IBM Rhapsody 라이선스 계약을 통해 커스터마이징 한 RapidAUTO 솔루션을 제공하며 ASPICE, ISO26262, Classic AUTOSAR
          개발이 가능한 툴을 통해 자동차 OEM 양산 납품, 국제 인증을 받기 위한 산출물 확보가 가능하도록 컨설팅 업무 수행
          설계 도구에서 인증에 필요한 성적서를 자동으로 작성하는 IBM Lifecycle Optimization 도구 유지보수
          
 layout: list
    content:
      - layout: right
        title: Hyundai-Autoever
        sub_title: Cybersecurity Manager (직급 책임)
        caption: 2021.05 ~ 현재
        link: https://www.hyundai-autoever.com
        quote: >
          미래차 성장 동력의 한 축인 인포테인먼트 산업 전반을 혁신적으로 리드합니다.
          GIS분야의 축적된 기술력과 노하우를 바탕으로 디지털 맵, 내비게이션SW, 자율주행 정밀지도를
          정교하게 제작하고 글로벌 위치 기반 콘텐츠와 통합 OTA 서비스를 제공하여 사용자가
          전혀 다른 모빌리티 서비스, 혁신적인 카 라이프를 경험할 수 있도록 합니다.
          
        description: | # this will include new lines to allow paragraphs
          현대기아차에 탑재되는 내비게이션SW 개발 프로세스 관리 및 개선 (개발자 400여명)
          아이오닉 6 유럽 차량 사이버보안 법규 인증, 신규 사양 보안 법규 영향도 검토
          
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      PM/PO 업무에 관심이 있으며 끊임없이 고민하고 근거를 기반으로 설득하는 것을 좋아합니다.
      컨설팅 업무, 프로세스 관리, Cybersecurity Manage 업무를 수행하면서 고객사, 개발자, 리더급 인원과
      지속적으로 커뮤니케이션하며 업무가 원활히 수행될 수 있도록 협의하고 가장 효율적인 방안으로 진행하도록 노력하고 있습니다.
      iOS개발에 관심이 있어 개인적으로 swift 공부 중입니다. 잘 부탁드립니다.

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
